### ISSUE TITLE
Problem in distributing with -s and -l

### ISSUE THREAD

**Issue by RezaSR** [hashcat/statsprocessor#5]
Hi
I noticed some issue in sp, maybe I am wrong!
For Simplicity of describing the issue, I used a simple charset as "abc" and also disabled the markov.

Initial state:
./sp64.bin --markov-disable -1abc hashcat.hcstat ?1?1
a
b
c
aa
ab
ac
ba
bb
bc
ca
cb
cc

So there are 12 combinations. if I divide and distribute the task to 3 nodes (each process 4 combinations), I should use:
-s0 -l4
-s4 -l8
-s8 -l12

The result is:

./sp64.bin --markov-disable -1abc -s0 -l4 hashcat.hcstat ?1?1
a
b
c
aa

./sp64.bin --markov-disable -1abc -s4 -l8 hashcat.hcstat ?1?1
ab
ba
bb
bc

./sp64.bin --markov-disable -1abc -s8 -l12 hashcat.hcstat ?1?1
bc
ca
cb
cc

As you can see "bc" is generated twice and "ac" is not generated at all.
I also tested without --markov-disable and the result was the same, one word generated twice and one word did not generate.

Is there any workaround to solve the issue and correctly distribute the task?
I really appreciate your help.

**Comment by unix-ninja** [comment]
Yeah, this is an issue with the way r_ctx was iterating. I created a patch and just made a pull request for it. That should fix your problem.

**Comment by RezaSR** [comment]
thanx for your help, I will test it.

**Comment by jsteube** [comment]
Should be fixed
